- changed container name since it is used by zap_scan 	modified:   .github/workflows/zap.yaml

diff --git a/.github/workflows/zap.yaml b/.github/workflows/zap.yaml
--- a/.github/workflows/zap.yaml
+++ b/.github/workflows/zap.yaml
@@ -20,13 +20,13 @@ jobs:
       
       - name: run web app on port 3000
         run: |
-          docker rmi my-web-app:latest || true
-          docker build -t my-web-app:latest .
+          docker rmi my-web-app-baseline:latest || true
+          docker build -t my-web-app-baseline:latest .
           echo "Docker image built for web app"
-          docker run -d --name my-web-app -p 127.0.0.1:3000:3000 my-web-app:latest
-          echo "Waiting for web app..."
+          docker run -d --name my-web-app-baseline -p 127.0.0.1:3000:3000 my-web-app-baseline:latest
+          echo "Waiting for web app baseline..."
           until curl -sSf http://127.0.0.1:3000; do sleep 5; done
-          echo "Web app is ready"
+          echo "Web app baseline is ready"
       
       - name: ZAP Scan Baseline
         uses: zaproxy/action-baseline@master
@@ -36,9 +36,9 @@ jobs:
 
       - name: Delete web app
         run: |
-          docker rm -f my-web-app || echo "Docker image for Main branch not found"
-          docker rmi my-web-app:latest || true
-          echo "Web app deleted"
+          docker rm -f my-web-app-baseline || echo "Docker image for Main branch not found"
+          docker rmi my-web-app-baseline:latest || true
+          echo "Web app baseline deleted"
 
   zap_scan:
     runs-on: self-hosted
